import { CustomerProfile } from '@/types';

export const customerProfiles: CustomerProfile[] = [
  {
    name: 'Anna Müller',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'frustrated',
    difficulty: 3,
    issue: 'Kundin meldet kritischen Softwarefehler nach Update und erwartet schnellen Patch.',
    background: 'Berufstätige Mutter, wenig Zeit, erwartet schnelle Lösung',
  },
  {
    name: 'Thomas Weber',
    avatar: 'https://images.pexels.com/photos/1040880/pexels-photo-1040880.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'angry',
    difficulty: 4,
    issue: 'Kunde hat fehlerhafte Serviceabrechnung für Cloud-Ressourcen erhalten und fordert sofortige Klärung.',
    background: 'Geschäftsmann, sehr direkt, fordert sofortige Klärung',
  },
  {
    name: 'Lisa Schmidt',
    avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'neutral',
    difficulty: 2,
    issue: 'Kundin hat Fragen zur Einrichtung der Multi-Factor-Authentifizierung und möchte technische Details verstehen.',
    background: 'Studentin, technikaffin, möchte alles verstehen',
  },
  {
    name: 'Michael Klein',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'happy',
    difficulty: 1,
    issue: 'Kunde lobt die neue VM-Performance und hat Zusatzfragen zu Managed-Backup-Angeboten.',
    background: 'Zufriedener Kunde, möchte mehr über weitere Produkte erfahren',
  },
  {
    name: 'Sarah Hoffmann',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'angry',
    difficulty: 5,
    issue: 'Kundin erlebt wiederholte Netzwerkausfälle im Rechenzentrum und erwägt den Wechsel des Dienstleisters.',
    background: 'Langjährige Kundin, sehr unzufrieden, überlegt Kündigung',
  },
  {
    name: 'David Wagner',
    avatar: 'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'frustrated',
    difficulty: 3,
    issue: 'Kunde hat Unklarheiten bei Verlängerung des VMware-Supportvertrags und neuen Lizenzmodellen.',
    background: 'Treuer Kunde, will besten Tarif und verstehen',
  },
  {
    name: 'Julia Richter',
    avatar: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'frustrated',
    difficulty: 4,
    issue: 'Kundin hat Schwierigkeiten beim sicheren Online-Banking wegen veralteter TLS-Version auf dem Server.',
    background: 'Ältere Dame, wenig technikaffin, besorgt um Finanzen',
  },
  {
    name: 'Max Schulz',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'angry',
    difficulty: 3,
    issue: 'Kunde meldet Lieferverzögerung bei dringend benötigten Ersatzteilen für Storage-Cluster.',
    background: 'Selbstständiger Handwerker, angewiesen auf pünktliche Lieferung',
  },
  {
    name: 'Lena Fischer',
    avatar: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'neutral',
    difficulty: 2,
    issue: 'Kundin möchte Details zur Integration ihrer IoT-Geräte in das Unternehmens-IT-Monitoring.',
    background: 'Technikbegeisterte, automatisiert Zuhause, hat spezifische Fragen',
  },
  {
    name: 'Paul Neumann',
    avatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'frustrated',
    difficulty: 4,
    issue: 'Kunde zweifelt an der Wirksamkeit des angebotenen EDR-Systems und fordert unabhängige Pen-Test-Berichte.',
    background: 'Wissenschaftler, akzeptiert nur belastbare Daten',
  },
  {
    name: 'Jan Schäfer',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'angry',
    difficulty: 4,
    issue: 'Kunde berichtet Datenverlust nach fehlgeschlagenem Backup und verlangt Restore innerhalb weniger Stunden.',
    background: 'IT-Leiter, Betriebsstillstand droht',
  },
  {
    name: 'Maria Köhler',
    avatar: 'https://images.pexels.com/photos/1838119/pexels-photo-1838119.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'frustrated',
    difficulty: 3,
    issue: 'Kundin kämpft mit instabiler VPN-Verbindung für Remote-Mitarbeiter.',
    background: 'HR-Managerin, muss Home-Office ermöglichen',
  },
  {
    name: 'Patrick Braun',
    avatar: 'https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'neutral',
    difficulty: 2,
    issue: 'Kunde möchte Beratung zur Migration seiner On-Prem-Server in die Cloud.',
    background: 'Start-up-Gründer, offen für moderne Lösungen',
  },
  {
    name: 'Katharina Wolf',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'happy',
    difficulty: 1,
    issue: 'Kundin ist zufrieden mit dem Helpdesk und fragt nach Schulung für neue ITSM-Plattform.',
    background: 'Teamleiterin Support, plant Weiterbildung',
  },
  {
    name: 'Jens Zimmermann',
    avatar: 'https://images.pexels.com/photos/1704481/pexels-photo-1704481.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'angry',
    difficulty: 5,
    issue: 'Kunde meldet Ransomware-Angriff und benötigt sofortige Incident-Response.',
    background: 'CIO Logistikunternehmen, hohe Ausfallkosten',
  },
  {
    name: 'Laura Bergmann',
    avatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'frustrated',
    difficulty: 3,
    issue: 'Kundin hat Fragen zum Lizenzmanagement nach Fusion zweier Standorte.',
    background: 'Controllerin, will rechtliche Risiken vermeiden',
  },
  {
    name: 'Daniel Kuhn',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'angry',
    difficulty: 4,
    issue: 'Kunde beschwert sich über wiederholte Ausfälle des Exchange-Servers.',
    background: 'Vertriebler, verliert Deals ohne E-Mail',
  },
  {
    name: 'Sabrina Hartmann',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'frustrated',
    difficulty: 3,
    issue: 'Kundin kann sich nicht in das Self-Service-Portal einloggen, Passwort-Reset schlägt fehl.',
    background: 'Office-Managerin, benötigt schnellen Zugang',
  },
  {
    name: 'Alexander König',
    avatar: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'happy',
    difficulty: 1,
    issue: 'Kunde bedankt sich für schnelle Server-Migration und interessiert sich für Monitoring-Add-ons.',
    background: 'Tech-Enthusiast, will Effizienz steigern',
  },
  {
    name: 'Sophie Krüger',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'neutral',
    difficulty: 2,
    issue: 'Kundin möchte detaillierte Dokumentation der API für Automatisierung.',
    background: 'Entwicklerin, plant CI/CD-Integration',
  },
  {
    name: 'Markus Beck',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'frustrated',
    difficulty: 4,
    issue: 'Kunde erhält ständig Fehlalarme vom SIEM und fordert Tuning.',
    background: 'Security-Analyst, Alarmflut belastet',
  },
  {
    name: 'Nadine Lorenz',
    avatar: 'https://images.pexels.com/photos/3775539/pexels-photo-3775539.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    mood: 'angry',
    difficulty: 4,
    issue: 'Kundin bemängelt fehlende Redundanz im Storage-Konzept nach Audit.',
    background: 'IT-Auditorin, kritisch auf Best Practices',
  },
];

export function getRandomCustomerProfile(): CustomerProfile {
  return customerProfiles[Math.floor(Math.random() * customerProfiles.length)];
}
